FROM node:20-alpine

# Install build tools for bcrypt native compilation
RUN apk add --no-cache python3 make g++

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY nest-cli.json tsconfig.json ./
COPY src ./src

ENV NODE_ENV=development

CMD ["npm", "run", "start:dev"]


