version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: SaasDB
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker

  ss-backend:
    build:
      context: ./ss-backend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-backend
    env_file:
      - ./ss-backend/.env
    environment:
      NODE_OPTIONS: ""
    command: node_modules/.bin/nest start --debug 0.0.0.0:9229 --watch
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./ss-backend/src:/usr/src/app/src
    depends_on:
      - postgres

  uam-backend:
    build:
      context: ./uam-backend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-uam-backend
    env_file:
      - ./uam-backend/.env
    environment:
      NODE_OPTIONS: ""
    command: node_modules/.bin/nest start --debug 0.0.0.0:9230 --watch
    ports:
      - "3001:3001"
      - "9230:9230"
    volumes:
      - ./uam-backend/src:/usr/src/app/src
    depends_on:
      - postgres

  thirdparty-backend:
    build:
      context: ./thirdparty-backend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-thirdparty-backend
    env_file:
      - ./thirdparty-backend/.env
    environment:
      NODE_OPTIONS: ""
    command: node_modules/.bin/nest start --debug 0.0.0.0:9231 --watch
    ports:
      - "5003:5003"
      - "9231:9231"
    volumes:
      - ./thirdparty-backend/src:/usr/src/app/src
    depends_on:
      - uam-backend

  ss-frontend:
    build:
      context: ./ss-frontend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-frontend
    env_file:
      - ./ss-frontend/.env
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./ss-frontend/src:/usr/src/app/src
    depends_on:
      - ss-backend
      - uam-backend

  uam-frontend:
    build:
      context: ./uam-frontend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-uam-frontend
    env_file:
      - ./uam-frontend/.env
    command: npm run start -- --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./uam-frontend/src:/usr/src/app/src
    depends_on:
      - uam-backend

  thirdparty-frontend:
    build:
      context: ./thirdparty-frontend
      dockerfile: Dockerfile.dev
    container_name: ag-saas-thirdparty-frontend
    env_file:
      - ./thirdparty-frontend/.env
    command: npm run start -- --host 0.0.0.0 --port 4300
    ports:
      - "4300:4300"
    volumes:
      - ./thirdparty-frontend/src:/usr/src/app/src
    depends_on:
      - thirdparty-backend

volumes:
  pgdata:


