FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY angular.json tsconfig*.json ./
COPY src ./src

ENV NODE_ENV=development

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]


